export const REQUEST_USER_SIGNUP = "REQUEST_USER_SIGNUP";
export const REQUEST_USER_SIGNUP_SUCCESS = "REQUEST_USER_SIGNUP_SUCCESS";
export const REQUEST_USER_SIGNUP_FAIL = "REQUEST_USER_SIGNUP_FAIL";
export const RESET_STATE = "RESET_STATE";