export const REQUEST_PROFILE_API = "REQUEST_PROFILE_API";
export const REQUEST_PROFILE_API_SUCCESS = "REQUEST_PROFILE_API_SUCCESS";
export const REQUEST_PROFILE_API_FAIL = "REQUEST_PROFILE_API_FAIL";
export const ADD_CHILD = "ADD_CHILD";
export const ADD_CHILD_REQUEST = "ADD_CHILD_REQUEST";
export const ADD_CHILD_REQUEST_FAIL = "ADD_CHILD_REQUEST";
export const REMOVE_CHILD = "REMOVE_CHILD";